# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=200)),
                ('lowest_price', models.IntegerField()),
                ('at_data', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
